name: 'publish'

on: [push]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          image: ext-alpine
          env: production

      - name: Publish to S3
        run: aws s3 sync public/. s3://shimmeringbee.io/ --cache-control max-age=120,no-cache,no-store,must-revalidate --delete
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}